### PR TITLE
Update gralde version

### LINKED ISSUE #4001: Update gradle version of serdes module
**Description:**
SerDes module uses gradle version 6.8.2, update it to match with other module version

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by MohamedSabthar**
## Purpose

Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/4001

## Checklist
- [x] Linked to an issue
- [ ] ~~Updated the changelog~~
- [ ] ~~Added tests~~
- [ ] ~~Updated the spec~~
- [ ] ~~Checked native-image compatibility~~

### CODE REVIEW

**Review by ThisaruGuruge — APPROVED** [review]

**Comment by ThisaruGuruge** [comment]
Shouldn't we update the Wrapper JAR with this change? I think we should.

**Comment by MohamedSabthar** [comment]
> Shouldn't we update the Wrapper JAR with this change? I think we should.

The Wrapper JAR file containing code for downloading the Gradle distribution. The jar picks the gradle distribution version from `gradle-wrapper.properties`. I don't think we need to update the wrapper jar.

**Comment by ThisaruGuruge** [comment]
> > Shouldn't we update the Wrapper JAR with this change? I think we should.
> 
> The Wrapper JAR file containing code for downloading the Gradle distribution. The jar picks the gradle distribution version from `gradle-wrapper.properties`. I don't think we need to update the wrapper jar.

No, that's incorrect. The Jar is committed, and uploaded for the usage. We should update it.

**Comment by MohamedSabthar** [comment]
PR: https://github.com/ballerina-platform/module-ballerina-serdes/pull/138

**Pull request merged**
